package com.medxplore.utils;

public interface QueryConstants {
	//String LOGIN_SQL = "SELECT userid,password FROM user_mst WHERE userid=? AND password=?";
	
	String COMMON_GENERIC_SQL = "SELECT * FROM COMMON_GENE_PARA WHERE KEY=?";
	
	String LOGIN_SQL = "SELECT USER_MST.USERID AS USERID,USER_MST.PWD AS PASSWORD, USER_MST.EMAILID AS EMAILID,"
			+ " USER_MST.FIRSTNAME AS FIRSTNAME, USER_MST.LASTNAME AS LASTNAME, USER_MST.ADDRESS AS ADDRESS,"
			+ " USER_MST.CONTACTNO AS CONTACTNO, ROLE_MST.ROLENAME AS ROLE,RIGHT_MST.RIGHTNAME AS RIGHT,RIGHT_MST.SCREEN AS SCREEN "
			+ "FROM USER_MST,ROLE_MST,RIGHT_MST,USER_ROLE_MAPPING,ROLE_RIGHT_MAPPING "
			+ "WHERE USER_MST.UID=USER_ROLE_MAPPING.UID AND ROLE_MST.ROLEID=USER_ROLE_MAPPING.ROLEID "
			+ "AND ROLE_MST.ROLEID=ROLE_RIGHT_MAPPING.ROLEID AND RIGHT_MST.RIGHTID=ROLE_RIGHT_MAPPING.RIGHTID AND USER_MST.USERID=? AND USER_MST.PWD=?;";
		//	returns userid, role, right, Screen.
	
	String REGISTER_USER_SQL = "INSERT INTO USER_MST (USERID,PWD,EMAILID,FIRSTNAME,LASTNAME,ADDRESS,CONTACTNO) values(?,?,?,?,?,?,?)";
	String UID_SQL = "SELECT UID FROM USER_MST WHERE USERID=?";
	String ROLEID_SQL = "SELECT ROLEID FROM ROLE_MST WHERE ROLENAME=?";
	String USER_ROLE_MAP_SQL = "INSERT INTO USER_ROLE_MAPPING(UID,ROLEID) VALUES(?,?)";
	String DELETE_USER_SQL = "DELETE FROM USER_MST WHERE USERID=?";
	
	String MAIN_MED_SQL = "SELECT MC.DESCR, M.MEDNAME, M.PACKSIZE, M.PRICE, M.SALTS, S.SNAME, S.SADDRESS, S.SCONTACTNO FROM MED_CATEGORY_MST MC, MED_MST M, STORE_MST S, MED_STORE_MAPPING MS WHERE M.MEDID=MS.MEDID AND S.SID=MS.SID AND M.CATEGORYID=MC.CATEGORYID AND MC.DESCR=? AND M.MEDNAME=?";
	
	String ALT_MED_LIST_SQL = "SELECT M.MEDNAME, M.PACKSIZE, M.PRICE, M.SALTS FROM MED_MST M WHERE M.MEDNAME!=? AND (?=ANY(SALTS) OR ?=ANY(SALTS))";
	
}
